services:
  - type: web
    name: secure-login-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python railway.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
